# For now build a static plot and display, then convert to python!

library(readr)
library(ggplot2)
library(magrittr)
library(scales)

ds <- read_csv("request-data.csv")
anom <- ds[ds$anomaly,]
  
ds %>%
  ggplot(aes(x=timestamp)) +
  geom_ribbon(aes(ymin = from, ymax=to), alpha=0.2) +
  geom_line(aes(y=value), colour="blue") +
  geom_point(data=anom, aes(x=timestamp, y=value), color="red") +
  scale_y_continuous(limits=c(20e6, 40e6),
                     labels=unit_format(unit="M", scale=1e-6, sep="")) +
  labs(x="Daily Observations", y="Requests",
       title="Actual Values versus Range of Expected Values",
       caption="GGPlot2 generated by Graham Williams")
ggsave("request-data.pdf", width=10)
#system("evince request-data.pdf")
ggsave("request-data.png", width=12)
system("mogrify -resize 640 request-data.png")
#system("display request-data.png")
